<?php

return [
    'categories' => [
        [
            'slug' => 'wellness',
            'name' => 'Wellness-устройства',
            'description' => 'Устройства для персонального мониторинга здоровья, восстановления, сна и физиологических показателей.',
            'position' => 10,
        ],
        [
            'slug' => 'peptidy',
            'name' => 'Пептиды',
            'description' => 'Пептидные соединения: зарегистрированные препараты, клинические исследования и экспериментальные позиции.',
            'position' => 20,
        ],
        [
            'slug' => 'vitaminy-i-dobavki',
            'name' => 'Витамины и добавки',
            'description' => 'Пероральные витаминно-минеральные комплексы и пищевые добавки.',
            'position' => 30,
        ],
        [
            'slug' => 'beauty',
            'name' => 'Beauty-продукты',
            'description' => 'Нутрикосметика, ориентированная прежде всего на кожу и эстетический уход.',
            'position' => 40,
        ],
        [
            'slug' => 'inektsionnye-preparaty',
            'name' => 'Инъекционные препараты',
            'description' => 'Профессиональные косметологические средства и препараты для эстетической медицины.',
            'position' => 50,
        ],
        [
            'slug' => 'ingalyatory',
            'name' => 'Ингаляторы',
            'description' => 'Системы для поддержки дыхательных путей.',
            'position' => 60,
        ],
    ],

    'products' => [
        [
            'category' => 'wellness',
            'name' => 'Кольца-датчики',
            'summary' => 'Сон, пульс, температура кожи, HRV, активность, стресс и восстановление. Удобны для круглосуточного пассивного трекинга.',
            'maturity' => 'Зрелая массовая категория.',
            'supplier' => 'Китай',
            'source_url' => 'https://www.made-in-china.com/price/prodetail_Smart-Ring_MQerqbREHyYo.html',
        ],
        [
            'category' => 'wellness',
            'name' => 'Браслеты-датчики',
            'summary' => 'Мониторинг сна, тренировочной нагрузки, пульса, HRV, активности и восстановления. Часто используются для спортивной аналитики.',
            'maturity' => 'Зрелая массовая категория.',
            'supplier' => 'Китай',
            'source_url' => 'https://ru.made-in-china.com/co_4p-touch/product_Medical-grade-ECG-blood-glucose-smart-bracelet-with-uric-acid-lipids-body-composition-sensor-for-family-F23_yiuyosigrg.html',
        ],
        [
            'category' => 'wellness',
            'name' => 'Мониторы уровня глюкозы (CGM)',
            'summary' => 'Непрерывное измерение глюкозы в межтканевой жидкости. Используются при диабете, а также в отдельных wellness-программах под медицинским контролем.',
            'maturity' => 'Клинически зрелая категория; существуют авторизованные системы, включая Dexcom G7.',
            'supplier' => 'Китай',
            'source_url' => 'https://ru.made-in-china.com/co_easterntrading-z/product_Continuous-Glucose-Monitor-15-Days-X24-Hoursmonitoring-Cgm_yyheuouesg.html',
        ],
        [
            'category' => 'wellness',
            'name' => 'EEG-устройства для сна и мозга',
            'summary' => 'Регистрация электрической активности мозга для оценки сна, нейрофидбэка, исследований внимания и восстановления.',
            'maturity' => 'Коммерческие решения существуют, но качество и глубина интерпретации сильно различаются.',
            'supplier' => 'Китай',
            'source_url' => 'https://www.alibaba.com/product-detail/Muse-S-Athena-EEG-Headband-Smart_1601717577282.html',
        ],
        [
            'category' => 'wellness',
            'name' => 'Системы фотобиомодуляции Red/NIR',
            'summary' => 'Воздействие красным и ближним инфракрасным светом. Применяются в домашних программах восстановления, кожи, мышц и общего wellness.',
            'maturity' => 'Сформировавшаяся потребительская категория; доказательность зависит от показания и параметров устройства.',
            'supplier' => 'Китай',
            'source_url' => 'https://bjhyetech.en.made-in-china.com/product/SxYUqsfOgrpD/China-Skin-Beauty-Pain-Relief-Infrared-Red-Light-Therapy-Lamp-660nm-850nm-IR-Light-LED-Facial-Light-Therapy-Device.html',
        ],
        [
            'category' => 'wellness',
            'name' => 'UV-сенсоры и UV-патчи',
            'summary' => 'Оценка индивидуального воздействия ультрафиолета и помощь в контроле времени нахождения на солнце.',
            'maturity' => 'Реально существующая носимая категория.',
            'supplier' => 'Китай',
            'source_url' => 'https://ru.made-in-china.com/co_firstsensor/product_FST100-UV-A-Smart-UV-Sensor_yyyngnihng.html',
        ],
        [
            'category' => 'wellness',
            'name' => 'Неинвазивные стимуляторы блуждающего нерва',
            'summary' => 'Нейромодуляция через наружную стимуляцию ветвей блуждающего нерва. Исследуется и применяется в отдельных медицинских и wellness-сценариях.',
            'maturity' => 'Существующая специализированная категория; показания зависят от конкретного устройства.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'wellness',
            'name' => 'Мониторы дыхания и SpO2',
            'summary' => 'Контроль сатурации, частоты дыхания и связанных параметров во сне, спорте и домашнем мониторинге.',
            'maturity' => 'Широко распространенная wearable-категория.',
            'supplier' => 'Китай',
            'source_url' => 'https://yimilife.en.made-in-china.com/product/zajRZxAvOPhQ/China-Medical-CE-Approved-ISO13485-System-Certificated-Fingertip-Pulse-Oximeter-Finger-Pulse-Oximeter.html',
        ],
        [
            'category' => 'wellness',
            'name' => 'Cuffless-мониторы давления',
            'summary' => 'Оценка артериального давления без традиционной надувной манжеты с помощью оптических, механических и алгоритмических методов.',
            'maturity' => 'Развивающаяся категория; точность и регуляторная валидация остаются ключевыми вопросами.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'wellness',
            'name' => 'Умные наушники с биосенсорами',
            'summary' => 'Hearables с датчиками пульса, температуры, движения и потенциально других биомаркеров.',
            'maturity' => 'Реальное и быстро развивающееся направление.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'wellness',
            'name' => 'Умные очки',
            'summary' => 'AR/AI-функции, камеры, аудио, навигация; биомониторинг пока менее зрелый и чаще экспериментальный.',
            'maturity' => 'Коммерчески зрелы как smart-glasses, но медицинская биосенсорика пока ранняя.',
            'supplier' => 'Китай',
            'source_url' => 'https://staranb.en.made-in-china.com/product/RtAYvGaKTqrT/China-CE-RoHS-Wholesale-Wearable-Devices-Custom-Ai-Enabled-13-Mega-Px-Video-Sony-Camera-Anti-Shake-Ora-Sun-Smart-Glasses-with-Microphone-Bluetooth.html',
        ],
        [
            'category' => 'wellness',
            'name' => 'Домашние body-composition сканеры',
            'summary' => 'Оценка массы тела, жировой и безжировой массы, воды и других параметров состава тела.',
            'maturity' => 'Зрелая потребительская категория; точность зависит от технологии.',
            'supplier' => 'Китай',
            'source_url' => 'https://zzshdz.en.made-in-china.com/product/jdLanlrVEFUO/China-Bia-Four-Electrode-Bioimpedance-Body-Fat-Composition-Analyzer-Scale.html',
        ],
        [
            'category' => 'wellness',
            'name' => 'Домашние диагностические станции',
            'summary' => 'Комплексный сбор показателей дома: температура, пульс, SpO2, ЭКГ, давление, дыхание и другие метрики.',
            'maturity' => 'Существуют отдельные коммерческие системы; рынок фрагментирован.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'wellness',
            'name' => 'Домашние анализаторы мочи',
            'summary' => 'Автоматизированный анализ тест-полосок или картриджей для отдельных показателей мочи с передачей данных в приложение.',
            'maturity' => 'Реально существующая нишевая категория.',
            'supplier' => 'Китай',
            'source_url' => 'https://huichaomed.en.made-in-china.com/product/iaApGSWoqzYD/China-2025-W-200b-Clinic-and-Home-Urinalysis-Machine-Digital-Urine-Analyzer-Semi-Automatic-Urine-Analyzer.html',
        ],
        [
            'category' => 'wellness',
            'name' => 'Биохимические smart-патчи',
            'summary' => 'Анализ пота и других биожидкостей для оценки лактата, электролитов, метаболитов и иных биомаркеров.',
            'maturity' => 'Развивающаяся категория; полноценная лаборатория на коже пока не стала массовым стандартом.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'wellness',
            'name' => 'Мультибиосенсорные патчи',
            'summary' => 'Одновременное измерение нескольких физиологических и/или биохимических параметров в одном носимом модуле.',
            'maturity' => 'В основном исследования, пилоты и ранние коммерческие решения.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'wellness',
            'name' => 'Датчики гидратации',
            'summary' => 'Оценка потери жидкости и признаков обезвоживания по поту, импедансу, температуре или комбинированным сигналам.',
            'maturity' => 'Развиваются; точность и переносимость между пользователями пока ограничены.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'wellness',
            'name' => 'Датчики электролитов через пот',
            'summary' => 'Измерение натрия, калия и других электролитов в поте для спорта и физиологического мониторинга.',
            'maturity' => 'Реальная технология, но пока преимущественно специализированная и исследовательская.',
            'supplier' => 'Китай',
            'source_url' => 'https://strider-tech.en.made-in-china.com/product/FmdrKOaTMSVj/China-Industrial-Online-Monitoring-Chloride-Ion-Selective-Sensor-Electrode-Digital-RS485-Water-Monitoring.html',
        ],
        [
            'category' => 'wellness',
            'name' => 'Датчики глюкозы через пот',
            'summary' => 'Попытка неинвазивной оценки глюкозы по поту без сенсора в подкожной ткани.',
            'maturity' => 'Исследовательская/прототипная технология; не эквивалент зрелым медицинским CGM.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'wellness',
            'name' => 'Носимые устройства для нейростимуляции',
            'summary' => 'Форм-факторы в виде колье, клипс и других носимых модулей для стимуляции нервной системы и автономной регуляции.',
            'maturity' => 'Категория существует, но пока не является единым устоявшимся классом.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'wellness',
            'name' => 'AI health / longevity assistant',
            'summary' => 'Программная экосистема, которая объединяет данные wearables, анализов, сна, активности и привычек и формирует персональные рекомендации.',
            'maturity' => 'Быстро развивающаяся сервисная категория; качество зависит от данных, алгоритмов и медицинской валидации.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'wellness',
            'name' => 'Система биоимпеданса МЕДАСС АВС-02',
            'summary' => 'Аппаратный биоимпедансный анализ состава тела для клинического и профилактического применения.',
            'maturity' => 'Серийно выпускаемая система.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'wellness',
            'name' => 'Датчик мониторинга сна',
            'summary' => 'Носимый пояс-трекер для оценки характеристик сна.',
            'maturity' => 'Серийная потребительская категория.',
            'supplier' => 'Китай',
            'source_url' => 'https://www.made-in-china.com/showroom/3e768a5e7716dde6/product-detailvajYRxeVhfky/China-Smart-Sleep-Tracker-Belt.html',
        ],
        [
            'category' => 'peptidy',
            'name' => 'Tirzepatide',
            'summary' => 'Снижение массы тела и гликемии за счет двойного агонизма GIP/GLP-1.',
            'maturity' => 'Клинически применяемый препарат.',
            'supplier' => 'Поставщик ПЕПТИДЫ',
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Retatrutide',
            'summary' => 'Исследуется для выраженного снижения массы тела и улучшения метаболических показателей; тройной агонист GLP-1/GIP/глюкагона.',
            'maturity' => 'Поздняя клиническая разработка; не считать стандартной терапией без актуальной регуляторной проверки.',
            'supplier' => 'Dailian huihai shengtong',
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'AHK-Cu',
            'summary' => 'Исследуется в контексте кожи, волос, регенерации и сигналов внеклеточного матрикса.',
            'maturity' => 'Экспериментальное/косметологическое направление; ограниченная клиническая база.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Adipotide',
            'summary' => 'Исследовался как средство воздействия на сосудистое снабжение жировой ткани для уменьшения жировой массы.',
            'maturity' => 'Доклинический/экспериментальный уровень; не одобренная терапия.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'BPC-157',
            'summary' => 'Заявляемые и исследуемые направления: заживление мягких тканей, ЖКТ, связок и сухожилий, противовоспалительные эффекты.',
            'maturity' => 'Преимущественно доклинические данные; не утвержденное стандартное лечение.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'TB-500 (Thymosin B4)',
            'summary' => 'Регенерация тканей, ангиогенез, восстановление мышц и сухожилий; исследовательский интерес к репаративным процессам.',
            'maturity' => 'Экспериментальная категория; не стандартная терапия.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'BPC-157 + TB-500',
            'summary' => 'Комбинация, продвигаемая для восстановления мягких тканей и ускорения репаративных процессов.',
            'maturity' => 'Комбинация без надежно установленной клинической эффективности.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'BPC-157 + GHK-Cu + TB-500',
            'summary' => 'Комбинированное направление: восстановление тканей, кожа, воспаление, регенерация.',
            'maturity' => 'Экспериментальная комбинация.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Bronchogen',
            'summary' => 'Позиционируется как пептидный биорегулятор дыхательной системы и бронхолегочной ткани.',
            'maturity' => 'Ограниченная международная доказательная база.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'CJC-1295 No DAC',
            'summary' => 'Стимуляция секреции гормона роста через GHRH-рецептор; интерес в восстановлении и композиции тела.',
            'maturity' => 'Экспериментальное/off-label направление; не стандартная wellness-терапия.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'CJC-1295 DAC',
            'summary' => 'Продленная стимуляция оси GH/IGF-1 за счет модификации DAC.',
            'maturity' => 'Исследовательское соединение; клиническое применение ограничено.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'GHK-Cu',
            'summary' => 'Кожа, заживление, ремоделирование внеклеточного матрикса, волосы; наиболее известен в дерматологическом и косметическом контексте.',
            'maturity' => 'Коммерчески используется в косметике; системные эффекты изучены слабее.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Chonluten',
            'summary' => 'Позиционируется как пептидный биорегулятор дыхательной системы.',
            'maturity' => 'Ограниченная международная клиническая доказательность.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Crystagen',
            'summary' => 'Позиционируется как пептидный биорегулятор иммунной системы.',
            'maturity' => 'Ограниченная доказательная база.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Cagrilintide',
            'summary' => 'Аналог амилина, исследуемый для снижения аппетита и массы тела.',
            'maturity' => 'Клиническая разработка; статус зависит от страны и комбинации.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Cardiogen',
            'summary' => 'Позиционируется для поддержки сердечной мышцы и сердечно-сосудистой системы.',
            'maturity' => 'Пептидный биорегулятор с ограниченной международной доказательной базой.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Cortagen',
            'summary' => 'Позиционируется для нейрорегуляции и поддержки функций головного мозга.',
            'maturity' => 'Ограниченная клиническая доказательность.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Cerebrolysin',
            'summary' => 'Нейропептидная смесь, применяемая в некоторых странах при неврологических состояниях; изучалась при инсульте, ЧМТ и когнитивных нарушениях.',
            'maturity' => 'Регуляторный статус и рекомендации различаются по странам.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Cagrilintide + Semaglutide',
            'summary' => 'Комбинация амилинового и GLP-1 механизма для усиления снижения массы тела и контроля аппетита.',
            'maturity' => 'Клиническая разработка; зависит от актуального регуляторного статуса.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'DSIP',
            'summary' => 'Исследовался в связи со сном, стрессом и нейроэндокринной регуляцией.',
            'maturity' => 'Экспериментальный пептид; клиническая доказательность ограничена.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'EPO',
            'summary' => 'Стимуляция эритропоэза и образования эритроцитов; используется в медицине при определенных анемиях.',
            'maturity' => 'Клинический препарат с серьезными рисками при неправильном применении.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Epitalon',
            'summary' => 'Исследуется и продвигается в контексте старения, сна, мелатонина и клеточного долголетия.',
            'maturity' => 'Экспериментальное longevity-направление; убедительная клиническая база ограничена.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'FOXO4',
            'summary' => 'Исследовательские пептидные подходы к удалению сенесцентных клеток через путь FOXO4-p53.',
            'maturity' => 'Доклиническое senolytic-направление; не одобренная терапия.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'HGH Fragment 176-191',
            'summary' => 'Фрагмент гормона роста, исследуемый преимущественно в контексте липолиза и жирового обмена.',
            'maturity' => 'Экспериментальный; клиническая эффективность для снижения веса не установлена.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Follistatin 344',
            'summary' => 'Связывание миостатина/активина; исследуется для роста мышечной массы и регуляции мышечной ткани.',
            'maturity' => 'Экспериментальное направление с потенциальными системными рисками.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'HCG',
            'summary' => 'Гормональный препарат, применяемый в репродуктивной медицине и отдельных эндокринологических сценариях.',
            'maturity' => 'Клинически применяется по медицинским показаниям; не является средством для самостоятельного wellness-применения.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Glutathione',
            'summary' => 'Антиоксидантная система, редокс-баланс и детоксикационные процессы; используется в различных медицинских и косметологических контекстах.',
            'maturity' => 'Доказательность зависит от показания и пути введения.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'GHRP-2',
            'summary' => 'Секретагог гормона роста через ghrelin/GHS-рецепторы.',
            'maturity' => 'Экспериментальное/off-label направление.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'GHRP-6',
            'summary' => 'Стимуляция секреции гормона роста и аппетита; действует через GHS-рецепторы.',
            'maturity' => 'Экспериментальное/off-label направление.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Gonadorelin',
            'summary' => 'Аналог GnRH для стимуляции гипофизарной секреции LH/FSH и диагностических/репродуктивных задач.',
            'maturity' => 'Медицинское применение зависит от формы, страны и показаний.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'HGH (Somatropin)',
            'summary' => 'Заместительная терапия при подтвержденном дефиците гормона роста и отдельных медицинских показаниях.',
            'maturity' => 'Клинический рецептурный препарат; использование вне показаний несет значимые риски.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Humanin',
            'summary' => 'Митохондриальный пептид, исследуемый в контексте нейропротекции, метаболизма, клеточного стресса и старения.',
            'maturity' => 'Преимущественно доклиническая/ранняя исследовательская стадия.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Hexarelin',
            'summary' => 'Сильный секретагог гормона роста, агонист GHS-рецепторов.',
            'maturity' => 'Исследовательское соединение; не стандартная терапия.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Ipamorelin',
            'summary' => 'Селективный секретагог GH; исследуется в контексте восстановления и оси GH/IGF-1.',
            'maturity' => 'Экспериментальное/off-label направление.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'IGF-1 LR3',
            'summary' => 'Длительно действующий аналог IGF-1, исследуемый для анаболических и клеточно-ростовых эффектов.',
            'maturity' => 'Research-only/экспериментальное применение; существенные риски.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Kisspeptin-10',
            'summary' => 'Регуляция репродуктивной оси через стимуляцию GnRH; исследуется при нарушениях фертильности и репродуктивной эндокринологии.',
            'maturity' => 'Клиническое исследовательское направление.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'KPV',
            'summary' => 'Фрагмент альфа-MSH с исследуемыми противовоспалительными эффектами, особенно в коже и ЖКТ.',
            'maturity' => 'Преимущественно доклинические/ранние данные.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'KPV + GHK-Cu + TB-500 + BPC-157',
            'summary' => 'Комбинация, ориентированная на воспаление, кожу и восстановление тканей.',
            'maturity' => 'Экспериментальная смесь без подтвержденной комплексной клинической эффективности.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Livagen',
            'summary' => 'Позиционируется как пептидный биорегулятор печени.',
            'maturity' => 'Ограниченная международная доказательная база.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Cartalax',
            'summary' => 'Позиционируется для поддержки хрящевой ткани и суставов.',
            'maturity' => 'Ограниченная международная доказательная база.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Liraglutide',
            'summary' => 'GLP-1-агонист для контроля гликемии и снижения массы тела.',
            'maturity' => 'Клинически применяемый рецептурный препарат.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'MOTs-c',
            'summary' => 'Митохондриальный пептид, исследуемый в контексте чувствительности к инсулину, метаболизма, физической работоспособности и старения.',
            'maturity' => 'Экспериментальная/доклиническая и ранняя исследовательская стадия.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Mazdutide',
            'summary' => 'Мультиагонистный метаболический препарат, исследуемый/применяемый в отдельных юрисдикциях для ожирения и метаболических нарушений.',
            'maturity' => 'Регуляторный статус зависит от страны; требуется актуальная проверка.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Prostamax',
            'summary' => 'Позиционируется как пептидный биорегулятор предстательной железы.',
            'maturity' => 'Ограниченная международная доказательная база.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'NAD+',
            'summary' => 'Кофактор клеточного энергетического обмена; longevity-направление связано с митохондриями, энергетикой и клеточным старением.',
            'maturity' => 'Клинические эффекты добавочного/инфузионного применения зависят от показания и остаются предметом исследований.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Snap-8',
            'summary' => 'Косметический пептид, используемый для визуального уменьшения мимических морщин за счет влияния на нейромышечную сигнализацию.',
            'maturity' => 'Косметическое применение; не системная терапия.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Oxytocin',
            'summary' => 'Гормон/нейропептид с установленным медицинским применением в акушерстве; также исследуется в социальном поведении и нейропсихиатрии.',
            'maturity' => 'Клинический препарат для конкретных показаний; экспериментальные применения требуют осторожности.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'PT-141',
            'summary' => 'Агонист меланокортиновых рецепторов для сексуальной функции; бремеланотид имеет клиническое применение при определенном показании.',
            'maturity' => 'Клинический/рецептурный статус зависит от формы и страны.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'P21',
            'summary' => 'Экспериментальный нейротрофический пептид, изучаемый в моделях нейрогенеза, когнитивных функций и нейродегенерации.',
            'maturity' => 'Доклиническое исследовательское направление.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Pancragen',
            'summary' => 'Позиционируется как пептидный биорегулятор поджелудочной железы.',
            'maturity' => 'Ограниченная международная доказательная база.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Pinealon',
            'summary' => 'Позиционируется как нейропептидный биорегулятор для когнитивной поддержки и нервной системы.',
            'maturity' => 'Ограниченная международная доказательная база.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'ARA-290',
            'summary' => 'Пептид, производный от эритропоэтина, исследуемый для тканезащитных и противовоспалительных эффектов, включая нейропатическую боль.',
            'maturity' => 'Клиническое исследовательское направление; не стандартная терапия.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Selank',
            'summary' => 'Исследуется/применяется в отдельных странах как анксиолитический нейропептид; направления включают тревогу, стресс и когнитивные функции.',
            'maturity' => 'Доказательная и регуляторная база неоднородна по странам.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Sermorelin',
            'summary' => 'Аналог GHRH, стимулирующий эндогенную секрецию гормона роста.',
            'maturity' => 'Медицинский/compounding-статус зависит от юрисдикции; применение требует врача.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Survodutide',
            'summary' => 'Двойной агонист GLP-1/глюкагоновых рецепторов, исследуемый для ожирения и метаболических заболеваний, включая MASH.',
            'maturity' => 'Клиническая разработка.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Tesamorelin',
            'summary' => 'Аналог GHRH, используемый для уменьшения висцерального жира при определенном медицинском показании у людей с ВИЧ.',
            'maturity' => 'Клинически применяемый рецептурный препарат для конкретного показания.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Thymosin Alpha-1',
            'summary' => 'Иммуномодулирующий пептид; используется/исследуется при инфекциях, иммунных нарушениях и как адъювант в отдельных странах.',
            'maturity' => 'Регуляторный статус различается по странам.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Testagen',
            'summary' => 'Позиционируется как пептидный биорегулятор мужской репродуктивной системы/тестикулярной ткани.',
            'maturity' => 'Ограниченная международная доказательная база.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Thymalin',
            'summary' => 'Пептидный препарат тимуса, используемый/продвигаемый как иммуномодулятор в отдельных странах.',
            'maturity' => 'Международная доказательная и регуляторная база ограничена.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Teriparatide',
            'summary' => 'Фрагмент паратиреоидного гормона PTH(1-34), стимулирующий образование костной ткани.',
            'maturity' => 'Клинически применяемый препарат при определенных формах остеопороза.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Vilon',
            'summary' => 'Позиционируется как короткий пептидный биорегулятор иммунной системы и тимуса.',
            'maturity' => 'Ограниченная международная доказательная база.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'VIP',
            'summary' => 'Вазоактивный интестинальный пептид; исследуется в сосудистой, иммунной, дыхательной и нейроэндокринной регуляции.',
            'maturity' => 'Специализированное исследовательское/медицинское направление; не типичный wellness-препарат.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Semax',
            'summary' => 'Нейропептид, используемый/исследуемый в отдельных странах для нейропротекции и когнитивных функций.',
            'maturity' => 'Регуляторный статус и уровень доказательности различаются по странам.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'SS-31',
            'summary' => 'Митохондриально-направленный пептид elamipretide; исследуется при митохондриальных и сердечно-мышечных заболеваниях.',
            'maturity' => 'Клиническая разработка; статус зависит от конкретного показания и страны.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'LL-37',
            'summary' => 'Эндогенный антимикробный пептид; исследуется в иммунитете, инфекциях, заживлении и воспалении.',
            'maturity' => 'Экспериментальное направление; системное применение связано с рисками.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'SLU-PP-322',
            'summary' => 'Позиция из исходного списка; вероятно относится к исследовательским метаболическим соединениям.',
            'maturity' => 'Экспериментальная позиция; название требует верификации.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'AOD',
            'summary' => 'Обычно под AOD подразумевают AOD-9604, фрагмент гормона роста, исследованный для липолиза и снижения жировой массы.',
            'maturity' => 'Экспериментальное направление; значимый эффект снижения веса у людей убедительно не подтвержден.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => '5-Amino-1MQ',
            'summary' => 'Исследовательское соединение, ингибирующее NNMT; изучается в моделях жирового обмена, метаболизма и композиции тела.',
            'maturity' => 'Преимущественно доклиническое/research-only направление.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Lemon Bottle',
            'summary' => 'Продукт, продвигаемый в эстетической сфере как средство для локального уменьшения жировой ткани.',
            'maturity' => 'Не считать подтвержденным пептидным медицинским препаратом; безопасность и легальность инъекционного применения вызывают регуляторные вопросы.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'peptidy',
            'name' => 'Вода NAD+',
            'summary' => 'Питьевая форма NAD+ из исходного списка позиций.',
            'maturity' => 'Позиция требует уточнения состава и статуса.',
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'vitaminy-i-dobavki',
            'name' => 'Gyno Ferro Sanol',
            'summary' => 'Железосодержащий комплекс с фолиевой кислотой и витамином B12. Используется для восполнения дефицита железа и поддержки кроветворения.',
            'maturity' => null,
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'vitaminy-i-dobavki',
            'name' => 'Life Extension Skin Restoring Ceramides',
            'summary' => 'Добавка с церамидами для поддержки кожного барьера, увлажнённости и гладкости кожи.',
            'maturity' => null,
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'vitaminy-i-dobavki',
            'name' => 'Sorvagen Niacinamide + Collagen',
            'summary' => 'Ниацинамид, коллагеновые пептиды, гиалуроновая кислота, цинк, медь, биотин, селен и витамин C. Поддержка кожи, волос и ногтей.',
            'maturity' => null,
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'vitaminy-i-dobavki',
            'name' => 'Orzax Ocean Mood',
            'summary' => 'Комплекс с 5-HTP, пассифлорой, валерианой, мелиссой и витамином B6. Позиционируется для поддержки расслабления, сна и эмоционального состояния.',
            'maturity' => null,
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'vitaminy-i-dobavki',
            'name' => 'Life Extension Creatine Capsules',
            'summary' => 'Креатин в капсулах. Поддержка мышечной работоспособности, силовых показателей и энергетического обмена при физической нагрузке.',
            'maturity' => null,
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'beauty',
            'name' => 'BY LUA The White Gluta-C Collagen Peptide',
            'summary' => 'Beauty-комплекс с низкомолекулярным рыбным коллагеном, витамином C, L-цистином, гиалуроновой кислотой и глутатионом. Позиционируется для поддержки качества кожи и антиоксидантной защиты.',
            'maturity' => null,
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'beauty',
            'name' => 'Ever Green Glutathione Plus',
            'summary' => 'Нутрикосметический комплекс с глутатионом, низкомолекулярным рыбным коллагеном и витамином C. Позиционируется для антиоксидантной поддержки и ухода за кожей.',
            'maturity' => null,
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'beauty',
            'name' => 'Liposomal Glutathione + Low-Molecular Collagen',
            'summary' => 'Beauty-комплекс с липосомальным глутатионом, низкомолекулярным рыбным коллагеном и витамином C. Позиционируется для антиоксидантной поддержки и улучшения качества кожи.',
            'maturity' => null,
            'supplier' => 'Корея - Китай',
            'source_url' => 'https://www.tradekorea.com/product/detail/P818105/-Sparkle-Glutathione-Collagen-C.html',
        ],
        [
            'category' => 'inektsionnye-preparaty',
            'name' => 'Proluma R4 Collagen',
            'summary' => 'Профессиональный косметологический комплекс на основе коллагена с дополнительными компонентами. Позиционируется для увлажнения, регенерации и улучшения качества кожи.',
            'maturity' => null,
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'inektsionnye-preparaty',
            'name' => 'PDRN',
            'summary' => 'Профессиональные средства на основе полидезоксирибонуклеотидов. Используются в эстетической медицине для поддержки восстановления кожи, увлажнения и улучшения её качества.',
            'maturity' => null,
            'supplier' => 'Корея',
            'source_url' => 'https://www.tradekorea.com/product/detail/P856299/J-Aethel-PDRN-Repair-Ampoule-30mL,-Korean-Facial-Ampoule.html',
        ],
        [
            'category' => 'inektsionnye-preparaty',
            'name' => 'Rejuran Skin Booster',
            'summary' => 'Профессиональный skin-booster на основе PDRN/полинуклеотидных компонентов. Основные направления: регенерация, увлажнение и улучшение текстуры кожи.',
            'maturity' => null,
            'supplier' => 'Корея',
            'source_url' => 'https://www.tradekorea.com/product/detail/P853619/REJURAN-Synergy-Skin-booster.html',
        ],
        [
            'category' => 'inektsionnye-preparaty',
            'name' => 'Jeunetique Exo',
            'summary' => 'Профессиональный косметологический продукт с экзосомной концепцией. Позиционируется для восстановления кожи и поддержки регенеративных процессов.',
            'maturity' => null,
            'supplier' => 'Корея',
            'source_url' => 'https://www.tradekorea.com/product/detail/P840508/Jeunetique-Exo-Exosome--SKINBOOSTER.html',
        ],
        [
            'category' => 'inektsionnye-preparaty',
            'name' => 'Jeunetique NAD+',
            'summary' => 'Профессиональный косметологический продукт с NAD+-компонентом. Позиционируется в anti-age и восстановительных программах.',
            'maturity' => null,
            'supplier' => 'Корея',
            'source_url' => 'https://meamoshop.com/newly-curated/jeunetique-nad/',
        ],
        [
            'category' => 'inektsionnye-preparaty',
            'name' => 'Dermagen Plus Cinderella Healer',
            'summary' => 'Профессиональный комплекс, заявленный для увлажнения, сияния кожи, поддержки коллагена и ревитализации.',
            'maturity' => null,
            'supplier' => null,
            'source_url' => null,
        ],
        [
            'category' => 'inektsionnye-preparaty',
            'name' => 'HyalMass Aqua-Exosome',
            'summary' => 'Профессиональный продукт с экзосомной концепцией для увлажнения, восстановления и улучшения внешнего состояния кожи.',
            'maturity' => null,
            'supplier' => 'Корея',
            'source_url' => 'https://www.tradekorea.com/product/detail/P856045/Hyalmass-aqua-Exosome---Exosome-Skin-Booster.html',
        ],
        [
            'category' => 'inektsionnye-preparaty',
            'name' => 'Renuvol Premium PDO Booster',
            'summary' => 'Профессиональный PDO-booster. Позиционируется для улучшения качества кожи, поддержки коллагена, увлажнения и регенерации.',
            'maturity' => null,
            'supplier' => 'Zhejiang Xianju Pharmaceutical',
            'source_url' => 'https://www.xjpharma.com/en/',
        ],
        [
            'category' => 'inektsionnye-preparaty',
            'name' => 'Биоидентичные гормональные пеллеты',
            'summary' => 'Маленькие стерильные импланты с гормоном, которые устанавливают под кожу и которые постепенно высвобождают гормон в течение нескольких месяцев. Чаще всего используют эстрадиол и тестостерон.',
            'maturity' => 'Применяется по медицинским показаниям под контролем врача.',
            'supplier' => 'Humanwell Pharmaceutical',
            'source_url' => 'https://humanwell.com.cn/Partnership.html',
        ],
        [
            'category' => 'ingalyatory',
            'name' => 'LMAX CLIMATIC',
            'summary' => 'Не электронная сигарета и не лекарственный ингалятор. Производитель позиционирует устройство как ежедневную систему для поддержки очищения дыхательных путей: одноразовый блистер, глубокий вдох около 5 секунд и задержка дыхания около 5 секунд.',
            'maturity' => 'Потребительский продукт производителя.',
            'supplier' => null,
            'source_url' => 'https://www.climatichealth.com/products/l-max',
        ],
    ],
];
