export default {
    Undo: 'Отменить',
    Redo: 'Повторить',
    Blocks: 'Блок',
    Paragraph: 'Абзац',
    'Heading 1': 'Заголовок 1',
    'Heading 2': 'Заголовок 2',
    'Heading 3': 'Заголовок 3',
    'Heading 4': 'Заголовок 4',
    'Heading 5': 'Заголовок 5',
    'Heading 6': 'Заголовок 6',
    Preformatted: 'Моноширинный',
    Div: 'Блок div',
    Pre: 'Код',
    Bold: 'Жирный',
    Italic: 'Курсив',
    Underline: 'Подчёркнутый',
    Strikethrough: 'Зачёркнутый',
    'Bullet list': 'Маркированный список',
    'Numbered list': 'Нумерованный список',
    Blockquote: 'Цитата в рамке',
    'Horizontal line': 'Горизонтальная линия',
    'Clear formatting': 'Убрать оформление',
    'Source code': 'Исходный HTML',
    'Insert/edit link': 'Ссылка',
    'Insert/Edit Link': 'Ссылка',
    'Insert link': 'Вставить ссылку',
    'Text to display': 'Текст ссылки',
    Title: 'Подсказка',
    Url: 'Адрес',
    'Open link in...': 'Открывать в…',
    'Current window': 'Текущем окне',
    'New window': 'Новом окне',
    None: 'Не задано',
    'Insert/edit image': 'Картинка',
    'Insert/Edit Image': 'Картинка',
    Image: 'Картинка',
    Source: 'Адрес',
    'Alternative description': 'Описание для незрячих',
    'Image description': 'Описание картинки',
    Dimensions: 'Размеры',
    Width: 'Ширина',
    Height: 'Высота',
    'Constrain proportions': 'Сохранять пропорции',
    General: 'Основное',
    Advanced: 'Дополнительно',
    Upload: 'Загрузка',
    'Browse files': 'Выбрать файл',
    'Drop an image here': 'Перетащите картинку сюда',
    'Insert/edit media': 'Видео',
    'Insert/Edit Media': 'Видео',
    'Paste your embed code below:': 'Вставьте код для встраивания:',
    Embed: 'Код',
    Media: 'Видео',
    Table: 'Таблица',
    'Insert table': 'Вставить таблицу',
    'Table properties': 'Свойства таблицы',
    'Delete table': 'Удалить таблицу',
    Row: 'Строка',
    Column: 'Столбец',
    Cell: 'Ячейка',
    'Insert row before': 'Строку выше',
    'Insert row after': 'Строку ниже',
    'Delete row': 'Удалить строку',
    'Insert column before': 'Столбец слева',
    'Insert column after': 'Столбец справа',
    'Delete column': 'Удалить столбец',
    'Header cell': 'Ячейка заголовка',
    Cols: 'Столбцов',
    Rows: 'Строк',
    'Find and replace': 'Найти и заменить',
    Find: 'Найти',
    'Replace with': 'Заменить на',
    Replace: 'Заменить',
    'Replace all': 'Заменить все',
    'Match case': 'Учитывать регистр',
    Previous: 'Назад',
    Next: 'Вперёд',
    Save: 'Сохранить',
    Cancel: 'Отмена',
    Close: 'Закрыть',
    Ok: 'ОК',
    'Rich Text Area': 'Текст страницы',
    'Rich Text Area. Press ALT-0 for help.': 'Текст страницы. ALT-0 — справка.',
    'Reveal or hide additional toolbar items': 'Показать остальные кнопки',
    'Image uploading...': 'Загружаю картинку…',
    'Image upload failed': 'Не удалось загрузить картинку',
}
